/* Generated by scripts/discover-nodes.mjs. Do not edit. */
'use client';
import type React from 'react';
import type { BodyProps } from '../kit';
import type { NodeMeta } from '@/lib/node-meta';
import { AssemblerBody } from '../assembler/body';
import { AudioAnalysisBody } from '../audio-analysis/body';
import { AudioInputBody } from '../audio-input/body';
import { AudioMixBody } from '../audio-mix/body';
import { SceneBreakdownBody } from '../breakdown/body';
import { CaptionExportBody } from '../caption-export/body';
import { ComposeBody } from '../compose/body';
import { InputTriggerBody } from '../input/body';
import { LayerBody } from '../layer/body';
import { ExportBody } from '../mp4-export/body';
import { PlatesBody } from '../plates/body';
import { ScreenwriterBody } from '../screenwriter/body';
import { StaticScriptBody } from '../script/body';
import { SetBody } from '../set/body';
import { StockMediaBody } from '../stock/body';
import { TranscribeBody } from '../transcribe/body';
import { TtsBody } from '../tts/body';
import { VideoOutputBody } from '../video-output/body';
import { WebFetcherBody } from '../web/body';
import { PlateStore } from '../plates/PlateStore';
import { BeatEditorDialog } from '../screenwriter/BeatEditorDialog';
import { SceneEditorDialog } from '../script/SceneEditorDialog';
import { SetMemberDialog } from '../set/MemberDialog';
import { registerHyperframesClient } from '../hyperframes-engine/register.client';
import { registerRemotionClient } from '../remotion-engine/register.client';

export const NODE_BODIES: Record<string, React.FC<BodyProps>> = {
  'core/timeline-assembler': AssemblerBody,
  'core/audio-analysis': AudioAnalysisBody,
  'core/audio-input': AudioInputBody,
  'core/audio-mix': AudioMixBody,
  'core/scene-breakdown': SceneBreakdownBody,
  'core/caption-export': CaptionExportBody,
  'core/compose': ComposeBody,
  'core/input-trigger': InputTriggerBody,
  'core/layer': LayerBody,
  'core/mp4-export': ExportBody,
  'core/plates': PlatesBody,
  'core/screenwriter': ScreenwriterBody,
  'core/static-script': StaticScriptBody,
  'core/set': SetBody,
  'core/stock-media': StockMediaBody,
  'core/transcribe': TranscribeBody,
  'core/tts-engine': TtsBody,
  'core/video-output': VideoOutputBody,
  'core/web-fetcher': WebFetcherBody,
};

export const NODE_OVERLAYS: React.FC[] = [
  PlateStore,
  BeatEditorDialog,
  SceneEditorDialog,
  SetMemberDialog,
];

export const NODE_META: Record<string, NodeMeta> = {
  'core/timeline-assembler': { icon: 'layers', group: 'output' },
  'core/audio-analysis': { icon: 'wave', group: 'audio' },
  'core/audio-input': { icon: 'mic', group: 'audio' },
  'core/audio-mix': { icon: 'wave', group: 'audio' },
  'core/scene-breakdown': { icon: 'bot', group: 'script' },
  'core/caption-export': { icon: 'down', group: 'output' },
  'core/compose': { icon: 'layers', group: 'visual' },
  'core/input-trigger': { icon: 'bolt', group: 'source' },
  'core/layer': { icon: 'layers', group: 'visual' },
  'core/mp4-export': { icon: 'down', group: 'output' },
  'core/plates': { icon: 'brush', group: 'visual' },
  'core/screenwriter': { icon: 'bot', group: 'script' },
  'core/static-script': { icon: 'doc', group: 'script' },
  'core/set': { icon: 'brush', group: 'visual' },
  'core/stock-media': { icon: 'screen', group: 'visual' },
  'core/transcribe': { icon: 'wave', group: 'audio' },
  'core/tts-engine': { icon: 'wave', group: 'audio' },
  'core/video-output': { icon: 'screen', group: 'output', layout: 'wide' },
  'core/web-fetcher': { icon: 'doc', group: 'source' },
};

/** What a capsule registers in the browser beyond its body: an engine's player and preview. */
export const NODE_CLIENT_REGISTRATIONS: (() => void)[] = [
  registerHyperframesClient,
  registerRemotionClient,
];
