/* Generated by scripts/discover-nodes.mjs. Do not edit. */
'use client';
import type React from 'react';
import type { BodyProps } from '../kit';
import type { NodeMeta } from '@/lib/node-meta';
import { CaptionExportBody } from '../caption-export/body';
import { ExportBody } from '../mp4-export/body';
import { TranscribeBody } from '../transcribe/body';
import { TtsBody } from '../tts/body';
import { VideoOutputBody } from '../video-output/body';
import { registerHyperframesClient } from '../hyperframes-engine/register.client';
import { registerRemotionClient } from '../remotion-engine/register.client';

export const NODE_BODIES: Record<string, React.FC<BodyProps>> = {
  'core/caption-export': CaptionExportBody,
  'core/mp4-export': ExportBody,
  'core/transcribe': TranscribeBody,
  'core/tts-engine': TtsBody,
  'core/video-output': VideoOutputBody,
};

export const NODE_OVERLAYS: React.FC[] = [

];

export const NODE_META: Record<string, NodeMeta> = {
  'core/caption-export': { icon: 'down', group: 'output' },
  'core/mp4-export': { icon: 'down', group: 'output' },
  'core/transcribe': { icon: 'wave', group: 'audio' },
  'core/tts-engine': { icon: 'wave', group: 'audio' },
  'core/video-output': { icon: 'screen', group: 'output', layout: 'wide' },
};

/** What a capsule registers in the browser beyond its body: an engine's player and preview. */
export const NODE_CLIENT_REGISTRATIONS: (() => void)[] = [
  registerHyperframesClient,
  registerRemotionClient,
];
