/* Generated by scripts/discover-nodes.mjs. Do not edit. */
import { registerNodeType, registerRetiredNodeType, type AnyNodeDefinition, type RetiredNodeType } from '@/core/nodes/definition';
import { registerContracts } from '@/contracts';
import { registerDocMigrations } from '../migrations';
import { captionExport } from '../caption-export/node';
import { mp4Export } from '../mp4-export/node';
import { transcribe } from '../transcribe/node';
import { ttsEngine } from '../tts/node';
import { videoOutput } from '../video-output/node';
import { CaptionExportErrorCode } from '../caption-export/errors';
import { Mp4ExportErrorCode } from '../mp4-export/errors';
import { TranscribeErrorCode } from '../transcribe/errors';
import { TtsErrorCode } from '../tts/errors';

export const ALL_NODES: AnyNodeDefinition[] = [
  captionExport,
  mp4Export,
  transcribe,
  ttsEngine,
  videoOutput,
] as unknown as AnyNodeDefinition[];

const expectedIds = ["core/caption-export","core/mp4-export","core/transcribe","core/tts-engine","core/video-output"];
ALL_NODES.forEach((definition, index) => {
  if (definition.type !== expectedIds[index]) throw new Error('node manifest id "' + expectedIds[index] + '" does not match definition type "' + definition.type + '"');
});

/** The folders of user-brought files a node reads (music, voice, clips): name → env override and file kinds. */
export const NODE_LIBRARIES: Record<string, { env: string; extensions: readonly string[] }> = {};

/** What a node declares about itself beyond its ports, for the hub: which node carries the IR, the preview, the file export. */
export const NODE_FEATURES: Record<string, string[]> = {
  "core/caption-export": [],
  "core/mp4-export": [
    "history-file-export"
  ],
  "core/transcribe": [],
  "core/tts-engine": [],
  "core/video-output": [
    "history-preview"
  ]
};

/**
 * The failures each capsule owns. A code that belongs to one node lives in that node's errors.ts
 * beside its strings in the capsule's own locales; core carries only what core and the provider
 * layer raise. Listed here so a test can check every one of them can be shown to a person.
 */
export const NODE_ERROR_CODES: Record<string, string[]> = {
  "core/caption-export": [],
  "core/mp4-export": [],
  "core/transcribe": [],
  "core/tts-engine": []
};
NODE_ERROR_CODES['core/caption-export'] = Object.values(CaptionExportErrorCode);
NODE_ERROR_CODES['core/mp4-export'] = Object.values(Mp4ExportErrorCode);
NODE_ERROR_CODES['core/transcribe'] = Object.values(TranscribeErrorCode);
NODE_ERROR_CODES['core/tts-engine'] = Object.values(TtsErrorCode);

/** Node types that are gone, and what became of them (nodes/retired.json). */
export const RETIRED_NODES: Record<string, RetiredNodeType> = {
  "core/art-director": {
    "since": "2026-09-10"
  },
  "core/audio-analysis": {
    "since": "2026-09-14"
  },
  "core/audio-input": {
    "since": "2026-09-14"
  },
  "core/audio-mix": {
    "since": "2026-09-14"
  },
  "core/captions": {
    "since": "2026-09-12"
  },
  "core/cast": {
    "since": "2026-09-12"
  },
  "core/compose": {
    "since": "2026-09-14"
  },
  "core/cover-export": {
    "since": "2026-09-10"
  },
  "core/github-fetcher": {
    "since": "2026-09-13"
  },
  "core/hyperframes-engine": {
    "since": "2026-09-12"
  },
  "core/illustrator": {
    "since": "2026-09-13"
  },
  "core/input-trigger": {
    "since": "2026-09-14"
  },
  "core/layer": {
    "since": "2026-09-14"
  },
  "core/llm-provider": {
    "since": "2026-09-12"
  },
  "core/plates": {
    "since": "2026-09-14"
  },
  "core/remotion-engine": {
    "since": "2026-09-12"
  },
  "core/scene-breakdown": {
    "since": "2026-09-14"
  },
  "core/screenwriter": {
    "since": "2026-09-14"
  },
  "core/set": {
    "since": "2026-09-14"
  },
  "core/static-script": {
    "since": "2026-09-14"
  },
  "core/stock-media": {
    "since": "2026-09-14"
  },
  "core/style": {
    "since": "2026-09-12"
  },
  "core/timeline-assembler": {
    "since": "2026-09-14"
  },
  "core/tts-provider": {
    "since": "2026-09-12"
  },
  "core/web-fetcher": {
    "since": "2026-09-14"
  }
};

/** Nodes speak the video contracts, so registering them registers what runs on their wires first. */
export function registerNodes(): void {
  registerContracts();
  for (const definition of ALL_NODES) registerNodeType(definition);
  for (const [type, info] of Object.entries(RETIRED_NODES)) registerRetiredNodeType(type, info);
  registerDocMigrations();
}
