/* Generated by scripts/discover-nodes.mjs. Do not edit. */
import { registerNodeType, registerRetiredNodeType, type AnyNodeDefinition, type RetiredNodeType } from '@/core/nodes/definition';
import { registerDocMigrations } from '../migrations';
import { timelineAssembler } from '../assembler/node';
import { audioInput } from '../audio-input/node';
import { audioMix } from '../audio-mix/node';
import { sceneBreakdown } from '../breakdown/node';
import { captionExport } from '../caption-export/node';
import { captions } from '../captions/node';
import { githubFetcher } from '../github/node';
import { hyperframesEngine } from '../hyperframes-engine/node';
import { illustrator } from '../illustrator/node';
import { inputTrigger } from '../input/node';
import { llmProvider } from '../llm-provider/node';
import { mp4Export } from '../mp4-export/node';
import { remotionEngine } from '../remotion-engine/node';
import { screenwriter } from '../screenwriter/node';
import { staticScript } from '../script/node';
import { stockMedia } from '../stock/node';
import { transcribe } from '../transcribe/node';
import { ttsEngine } from '../tts/node';
import { ttsProvider } from '../tts-provider/node';
import { videoOutput } from '../video-output/node';
import { webFetcher } from '../web/node';
import { AssemblerErrorCode } from '../assembler/errors';
import { CaptionExportErrorCode } from '../caption-export/errors';
import { CaptionsErrorCode } from '../captions/errors';
import { GithubErrorCode } from '../github/errors';
import { Mp4ExportErrorCode } from '../mp4-export/errors';
import { TranscribeErrorCode } from '../transcribe/errors';
import { TtsErrorCode } from '../tts/errors';
import { WebErrorCode } from '../web/errors';

export const ALL_NODES: AnyNodeDefinition[] = [
  timelineAssembler,
  audioInput,
  audioMix,
  sceneBreakdown,
  captionExport,
  captions,
  githubFetcher,
  hyperframesEngine,
  illustrator,
  inputTrigger,
  llmProvider,
  mp4Export,
  remotionEngine,
  screenwriter,
  staticScript,
  stockMedia,
  transcribe,
  ttsEngine,
  ttsProvider,
  videoOutput,
  webFetcher,
] as unknown as AnyNodeDefinition[];

const expectedIds = ["core/timeline-assembler","core/audio-input","core/audio-mix","core/scene-breakdown","core/caption-export","core/captions","core/github-fetcher","core/hyperframes-engine","core/illustrator","core/input-trigger","core/llm-provider","core/mp4-export","core/remotion-engine","core/screenwriter","core/static-script","core/stock-media","core/transcribe","core/tts-engine","core/tts-provider","core/video-output","core/web-fetcher"];
ALL_NODES.forEach((definition, index) => {
  if (definition.type !== expectedIds[index]) throw new Error('node manifest id "' + expectedIds[index] + '" does not match definition type "' + definition.type + '"');
});

/** The folders of user-brought files a node reads (music, voice, clips): name → env override and file kinds. */
export const NODE_LIBRARIES: Record<string, { env: string; extensions: readonly string[] }> = {
  "voice": {
    "env": "NODECINE_VOICE_DIR",
    "extensions": [
      "mp3",
      "m4a",
      "aac",
      "wav",
      "ogg",
      "flac"
    ]
  },
  "music": {
    "env": "NODECINE_MUSIC_DIR",
    "extensions": [
      "mp3",
      "m4a",
      "aac",
      "wav",
      "ogg",
      "flac"
    ]
  },
  "clips": {
    "env": "NODECINE_CLIPS_DIR",
    "extensions": [
      "mp4",
      "webm",
      "mov",
      "m4v"
    ]
  }
};

/** What a node declares about itself beyond its ports, for the hub: which node carries the IR, the preview, the file export. */
export const NODE_FEATURES: Record<string, string[]> = {
  "core/timeline-assembler": [
    "history-ir"
  ],
  "core/audio-input": [],
  "core/audio-mix": [],
  "core/scene-breakdown": [],
  "core/caption-export": [],
  "core/captions": [],
  "core/github-fetcher": [],
  "core/hyperframes-engine": [],
  "core/illustrator": [],
  "core/input-trigger": [
    "batch-source"
  ],
  "core/llm-provider": [],
  "core/mp4-export": [
    "history-file-export"
  ],
  "core/remotion-engine": [],
  "core/screenwriter": [],
  "core/static-script": [],
  "core/stock-media": [],
  "core/transcribe": [],
  "core/tts-engine": [],
  "core/tts-provider": [],
  "core/video-output": [
    "history-preview"
  ],
  "core/web-fetcher": []
};

/**
 * The failures each capsule owns. A code that belongs to one node lives in that node's errors.ts
 * beside its strings in the capsule's own locales; core carries only what core and the provider
 * layer raise. Listed here so a test can check every one of them can be shown to a person.
 */
export const NODE_ERROR_CODES: Record<string, string[]> = {
  "core/timeline-assembler": [],
  "core/caption-export": [],
  "core/captions": [],
  "core/github-fetcher": [],
  "core/mp4-export": [],
  "core/transcribe": [],
  "core/tts-engine": [],
  "core/web-fetcher": []
};
NODE_ERROR_CODES['core/timeline-assembler'] = Object.values(AssemblerErrorCode);
NODE_ERROR_CODES['core/caption-export'] = Object.values(CaptionExportErrorCode);
NODE_ERROR_CODES['core/captions'] = Object.values(CaptionsErrorCode);
NODE_ERROR_CODES['core/github-fetcher'] = Object.values(GithubErrorCode);
NODE_ERROR_CODES['core/mp4-export'] = Object.values(Mp4ExportErrorCode);
NODE_ERROR_CODES['core/transcribe'] = Object.values(TranscribeErrorCode);
NODE_ERROR_CODES['core/tts-engine'] = Object.values(TtsErrorCode);
NODE_ERROR_CODES['core/web-fetcher'] = Object.values(WebErrorCode);

/** Node types that are gone, and what became of them (nodes/retired.json). */
export const RETIRED_NODES: Record<string, RetiredNodeType> = {
  "core/art-director": {
    "replacedBy": "core/illustrator",
    "since": "2026-09-10"
  },
  "core/cover-export": {
    "since": "2026-09-10"
  }
};

export function registerNodes(): void {
  for (const definition of ALL_NODES) registerNodeType(definition);
  for (const [type, info] of Object.entries(RETIRED_NODES)) registerRetiredNodeType(type, info);
  registerDocMigrations();
}
