/* Generated by scripts/discover-nodes.mjs. Do not edit. */
import { captionExportTranslations } from '../caption-export/locales';
import { hyperframesEngineTranslations } from '../hyperframes-engine/locales';
import { mp4ExportTranslations } from '../mp4-export/locales';
import { remotionEngineTranslations } from '../remotion-engine/locales';
import { transcribeTranslations } from '../transcribe/locales';
import { ttsTranslations } from '../tts/locales';
import { videoOutputTranslations } from '../video-output/locales';

/** Every string a node shows, by language: its name and description (node.<id>, node.desc.<id>) and its own labels. */
export const NODE_TRANSLATIONS: Record<string, Record<string, string>> = { en: {}, vi: {} };
for (const extension of [captionExportTranslations, hyperframesEngineTranslations, mp4ExportTranslations, remotionEngineTranslations, transcribeTranslations, ttsTranslations, videoOutputTranslations]) {
  Object.assign(NODE_TRANSLATIONS.en!, extension.en);
  Object.assign(NODE_TRANSLATIONS.vi!, extension.vi);
}
