/* Generated by scripts/discover-nodes.mjs. Do not edit. Server only. */
import type { NodeService } from '@/core/engine/services';
import { audioAnalysisServices } from '../audio-analysis/server';
import { audioInputServices } from '../audio-input/server';
import { audioMixServices } from '../audio-mix/server';
import { layerServices } from '../layer/server';
import { stockMediaServices } from '../stock/server';
import { transcribeServices } from '../transcribe/server';
import { webFetcherServices } from '../web/server';
import { registerHyperframesServer } from '../hyperframes-engine/register.server';
import { registerRemotionServer } from '../remotion-engine/register.server';

export const NODE_SERVICE_EXTENSIONS: Record<string, NodeService>[] = [
  audioAnalysisServices,
  audioInputServices,
  audioMixServices,
  layerServices,
  stockMediaServices,
  transcribeServices,
  webFetcherServices,
];

/** What a capsule registers on the server beyond its definition: an engine, a renderer. */
export const NODE_SERVER_REGISTRATIONS: (() => void)[] = [
  registerHyperframesServer,
  registerRemotionServer,
];
