/* Generated by scripts/discover-nodes.mjs. Do not edit. Server only. */
import type { NodeService } from '@/core/engine/services';
import { transcribeServices } from '../transcribe/server';
import { registerHyperframesServer } from '../hyperframes-engine/register.server';
import { registerRemotionServer } from '../remotion-engine/register.server';

export const NODE_SERVICE_EXTENSIONS: Record<string, NodeService>[] = [
  transcribeServices,
];

/** What a capsule registers on the server beyond its definition: an engine, a renderer. */
export const NODE_SERVER_REGISTRATIONS: (() => void)[] = [
  registerHyperframesServer,
  registerRemotionServer,
];
