/* Generated by scripts/discover-nodes.mjs. Do not edit. */
import { registerNodeType, type AnyNodeDefinition } from '@/core/nodes/definition';
import { timelineAssembler } from '../assembler/node';
import { audioInput } from '../audio-input/node';
import { audioMix } from '../audio-mix/node';
import { sceneBreakdown } from '../breakdown/node';
import { captionExport } from '../caption-export/node';
import { captions } from '../captions/node';
import { githubFetcher } from '../github/node';
import { hyperframesEngine } from '../hyperframes-engine/node';
import { illustrator } from '../illustrator/node';
import { inputTrigger } from '../input/node';
import { llmProvider } from '../llm-provider/node';
import { mp4Export } from '../mp4-export/node';
import { remotionEngine } from '../remotion-engine/node';
import { screenwriter } from '../screenwriter/node';
import { staticScript } from '../script/node';
import { stockMedia } from '../stock/node';
import { transcribe } from '../transcribe/node';
import { ttsEngine } from '../tts/node';
import { ttsProvider } from '../tts-provider/node';
import { videoOutput } from '../video-output/node';
import { webFetcher } from '../web/node';

export const ALL_NODES: AnyNodeDefinition[] = [
  timelineAssembler,
  audioInput,
  audioMix,
  sceneBreakdown,
  captionExport,
  captions,
  githubFetcher,
  hyperframesEngine,
  illustrator,
  inputTrigger,
  llmProvider,
  mp4Export,
  remotionEngine,
  screenwriter,
  staticScript,
  stockMedia,
  transcribe,
  ttsEngine,
  ttsProvider,
  videoOutput,
  webFetcher,
] as unknown as AnyNodeDefinition[];

const expectedIds = ["core/timeline-assembler","core/audio-input","core/audio-mix","core/scene-breakdown","core/caption-export","core/captions","core/github-fetcher","core/hyperframes-engine","core/illustrator","core/input-trigger","core/llm-provider","core/mp4-export","core/remotion-engine","core/screenwriter","core/static-script","core/stock-media","core/transcribe","core/tts-engine","core/tts-provider","core/video-output","core/web-fetcher"];
ALL_NODES.forEach((definition, index) => {
  if (definition.type !== expectedIds[index]) throw new Error('node manifest id "' + expectedIds[index] + '" does not match definition type "' + definition.type + '"');
});

export function registerNodes(): void {
  for (const definition of ALL_NODES) registerNodeType(definition);
}
