/* Generated by scripts/discover-capsules.mjs. Do not edit. */
'use client';
import { registerHyperframesClient } from '../hyperframes/register.client';

/** What each engine registers in the browser: its player and, for one of them, the still preview. */
export const ENGINE_CLIENT_REGISTRATIONS: (() => void)[] = [
  registerHyperframesClient,
];
