/* Generated by scripts/discover-capsules.mjs. Do not edit. */
import { hyperframesEngineTranslations } from '../hyperframes/locales';

/** Every string an engine shows, by language. */
export const ENGINE_TRANSLATIONS: Record<string, Record<string, string>> = { en: {}, vi: {} };
for (const extension of [hyperframesEngineTranslations]) {
  Object.assign(ENGINE_TRANSLATIONS.en!, extension.en);
  Object.assign(ENGINE_TRANSLATIONS.vi!, extension.vi);
}
