/* Generated by scripts/discover-capsules.mjs. Do not edit. Server only. */
import { registerHyperframesServer } from '../hyperframes/register.server';
import { registerRemotionServer } from '../remotion/register.server';

/** What each engine registers on the server: its renderer, its producer, the scripts it serves. */
export const ENGINE_SERVER_REGISTRATIONS: (() => void)[] = [
  registerHyperframesServer,
  registerRemotionServer,
];
