/* Generated by scripts/discover-templates.mjs. Do not edit. */
import type { LocalizedText } from '@/core/engine/document';

/** What the gallery card shows, and which files the template's own folder holds. */
export type TemplateDescriptor = {
  id: string;
  group: 'video';
  tagline: LocalizedText;
  tags: LocalizedText[];
  /** File inside `templates/<id>/` holding the graph the gallery opens. */
  workflow: string;
  /** File inside `templates/<id>/` holding the card art. */
  thumbnail: string;
};

/**
 * Every template this build ships. The id is the folder that owns it, so a template is added, moved
 * or removed by moving one folder — never by editing this list.
 */
export const TEMPLATES: TemplateDescriptor[] = [
  { id: 'article-summary', group: 'video', tagline: {"en":"Turn an article link into a narrated summary video grounded in the source.","vi":"Biến một đường link thành video tóm tắt có giọng đọc, bám sát nguồn."}, tags: ["9:16","30–45s",{"en":"English narration","vi":"Giọng đọc tiếng Anh"}], workflow: 'workflow.json', thumbnail: 'thumbnail.png' },
];
