/* Generated by scripts/discover-templates.mjs. Do not edit. */
import type { LocalizedText } from '@/core/engine/document';

/** Where a template starts: what a person already has when they open the gallery. */
export type TemplateGroup = 'link' | 'idea' | 'recording';

/** What the gallery card shows, and which files the template's own folder holds. */
export type TemplateDescriptor = {
  id: string;
  group: TemplateGroup;
  tagline: LocalizedText;
  tags: LocalizedText[];
  /** File inside `templates/<id>/` holding the graph the gallery opens. */
  workflow: string;
  /** File inside `templates/<id>/` holding the card art. */
  thumbnail: string;
};

/**
 * Every template this build ships. The id is the folder that owns it, so a template is added, moved
 * or removed by moving one folder — never by editing this list.
 */
export const TEMPLATES: TemplateDescriptor[] = [
  { id: 'article-summary', group: 'link', tagline: {"en":"Turn an article link into a narrated summary video grounded in the source.","vi":"Biến một đường link thành video tóm tắt có giọng đọc, bám sát nguồn."}, tags: ["9:16","30–45s",{"en":"English narration","vi":"Giọng đọc tiếng Anh"}], workflow: 'workflow.json', thumbnail: 'thumbnail.png' },
  { id: 'book-summary', group: 'link', tagline: {"en":"Paste a book link or your own notes; get a chapter-by-chapter summary that keeps its place in the book.","vi":"Dán link cuốn sách hoặc ghi chú của bạn; nhận bản tóm tắt theo chương, giữ đúng vị trí trong sách."}, tags: ["9:16","~90s",{"en":"Needs a model and a voice","vi":"Cần model và giọng đọc"}], workflow: 'workflow.json', thumbnail: 'thumbnail.png' },
  { id: 'quote-cards', group: 'idea', tagline: {"en":"Type a quote and who said it; the card animates itself. No model, no voice.","vi":"Gõ câu trích dẫn và người nói; tấm thẻ tự dựng động. Không cần model, không cần giọng đọc."}, tags: ["9:16","~12s",{"en":"No model needed","vi":"Không cần model"}], workflow: 'workflow.json', thumbnail: 'thumbnail.png' },
  { id: 'tech-digest', group: 'link', tagline: {"en":"Paste up to three links; get a short daily digest with a source on every item.","vi":"Dán tối đa ba đường link; nhận bản tin ngắn, mỗi tin có nhãn nguồn."}, tags: ["9:16","~60s",{"en":"Needs a model and a voice","vi":"Cần model và giọng đọc"}], workflow: 'workflow.json', thumbnail: 'thumbnail.png' },
];
