import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root = process.cwd();
const nodesDir = path.join(root, 'nodes');
const generatedDir = path.join(nodesDir, '.generated');
const folders = (await readdir(nodesDir, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.') && !entry.name.startsWith('_'))
  .map((entry) => entry.name)
  .sort();
const capsules = [];

for (const folder of folders) {
  const file = path.join(nodesDir, folder, 'node.manifest.json');
  let manifest;
  try { manifest = JSON.parse(await readFile(file, 'utf8')); }
  catch (error) {
    if (error?.code === 'ENOENT') continue;
    throw new Error(`${path.relative(root, file)}: ${error.message}`);
  }
  capsules.push({ folder, ...manifest });
}

const ids = new Set();
for (const item of capsules) {
  for (const key of ['id', 'definition', 'body', 'icon', 'group']) if (typeof item[key] !== 'string' || !item[key]) throw new Error(`${item.folder}/node.manifest.json: ${key} is required`);
  if (ids.has(item.id)) throw new Error(`duplicate node id: ${item.id}`);
  ids.add(item.id);
}

function imports(side) {
  const modules = new Map();
  for (const item of capsules) {
    const module = side === 'server' ? 'node' : (item.bodyModule || 'body');
    const name = side === 'server' ? item.definition : item.body;
    const key = `${item.folder}/${module}`;
    modules.set(key, [...(modules.get(key) || []), name]);
  }
  if (side === 'client') {
    for (const item of capsules.filter((entry) => entry.overlay)) {
      const key = `${item.folder}/${item.overlayModule || 'body'}`;
      modules.set(key, [...(modules.get(key) || []), item.overlay]);
    }
  }
  return [...modules].map(([module, names]) => `import { ${[...new Set(names)].join(', ')} } from '../${module}';`).join('\n');
}

const server = `/* Generated by scripts/discover-nodes.mjs. Do not edit. */
import { registerNodeType, type AnyNodeDefinition } from '@/core/nodes/definition';
${imports('server')}

export const ALL_NODES: AnyNodeDefinition[] = [
${capsules.map((item) => `  ${item.definition},`).join('\n')}
] as unknown as AnyNodeDefinition[];

const expectedIds = ${JSON.stringify(capsules.map((item) => item.id))};
ALL_NODES.forEach((definition, index) => {
  if (definition.type !== expectedIds[index]) throw new Error('node manifest id "' + expectedIds[index] + '" does not match definition type "' + definition.type + '"');
});

export function registerNodes(): void {
  for (const definition of ALL_NODES) registerNodeType(definition);
}
`;

const client = `/* Generated by scripts/discover-nodes.mjs. Do not edit. */
'use client';
import type React from 'react';
import type { BodyProps } from '../kit';
import type { NodeMeta } from '@/lib/node-meta';
${imports('client')}

export const NODE_BODIES: Record<string, React.FC<BodyProps>> = {
${capsules.map((item) => `  '${item.id}': ${item.body},`).join('\n')}
};

export const NODE_META: Record<string, NodeMeta> = {
${capsules.map((item) => `  '${item.id}': { icon: '${item.icon}', group: '${item.group}' },`).join('\n')}
};

export const NODE_OVERLAYS: React.FC[] = [
${capsules.filter((item) => item.overlay).map((item) => `  ${item.overlay},`).join('\n')}
];
`;

await mkdir(generatedDir, { recursive: true });
await Promise.all([
  writeFile(path.join(generatedDir, 'server.ts'), server),
  writeFile(path.join(generatedDir, 'client.ts'), client),
]);
console.log(`Discovered ${capsules.length} node capsules.`);
