/* Generated by scripts/discover-providers.mjs. Do not edit. */
import { defaultSettingsOf } from '@/core/providers/registry';
import { schemaFields } from '@/core/schema-form';
import type { ProviderDescriptor } from '../installed';
import { claudeCodeSettings, claudeCodeWidgets } from '../claude-code/settings';
import { elevenlabsSettings, elevenlabsWidgets } from '../elevenlabs/settings';
import { ollamaSettings, ollamaWidgets } from '../ollama/settings';
import { piperSettings, piperWidgets } from '../piper/settings';
import { systemTtsSettings, systemTtsWidgets } from '../system-tts/settings';
import { vbeeSettings, vbeeWidgets } from '../vbee/settings';

/**
 * Every provider this build ships, described from its own schema. The fields the node draws, the
 * settings a fresh node starts with and the rules the server validates against are one thing seen
 * three ways, so they cannot disagree.
 */
export const PROVIDERS: ProviderDescriptor[] = [
  { id: 'claude-code', kind: 'llm', nameKey: 'provider.claude-code', noteKey: 'provider.claude-code.note', settingsSchema: claudeCodeSettings, defaultSettings: defaultSettingsOf(claudeCodeSettings), fields: schemaFields(claudeCodeSettings), widgets: claudeCodeWidgets },
  { id: 'elevenlabs', kind: 'tts', nameKey: 'provider.elevenlabs', noteKey: 'provider.elevenlabs.note', settingsSchema: elevenlabsSettings, defaultSettings: defaultSettingsOf(elevenlabsSettings), fields: schemaFields(elevenlabsSettings), widgets: elevenlabsWidgets },
  { id: 'ollama', kind: 'llm', nameKey: 'provider.ollama', noteKey: 'provider.ollama.note', settingsSchema: ollamaSettings, defaultSettings: defaultSettingsOf(ollamaSettings), fields: schemaFields(ollamaSettings), widgets: ollamaWidgets },
  { id: 'piper', kind: 'tts', nameKey: 'provider.piper', noteKey: 'provider.piper.note', settingsSchema: piperSettings, defaultSettings: defaultSettingsOf(piperSettings), fields: schemaFields(piperSettings), widgets: piperWidgets },
  { id: 'system-tts', kind: 'tts', nameKey: 'provider.system-tts', noteKey: 'provider.system-tts.note', settingsSchema: systemTtsSettings, defaultSettings: defaultSettingsOf(systemTtsSettings), fields: schemaFields(systemTtsSettings), widgets: systemTtsWidgets },
  { id: 'vbee', kind: 'tts', nameKey: 'provider.vbee', noteKey: 'provider.vbee.note', settingsSchema: vbeeSettings, defaultSettings: defaultSettingsOf(vbeeSettings), fields: schemaFields(vbeeSettings), widgets: vbeeWidgets },
];
