/* Generated by scripts/discover-providers.mjs. Do not edit. */
import { claudeCodeTranslations } from '../claude-code/locales';
import { elevenlabsTranslations } from '../elevenlabs/locales';
import { ollamaTranslations } from '../ollama/locales';
import { piperTranslations } from '../piper/locales';
import { systemTtsTranslations } from '../system-tts/locales';
import { vbeeTranslations } from '../vbee/locales';

/** Every string a provider shows: its name, the line under the picker, and its own value labels. */
export const PROVIDER_TRANSLATIONS: Record<string, Record<string, string>> = { en: {}, vi: {} };
for (const extension of [claudeCodeTranslations, elevenlabsTranslations, ollamaTranslations, piperTranslations, systemTtsTranslations, vbeeTranslations]) {
  Object.assign(PROVIDER_TRANSLATIONS.en!, extension.en);
  Object.assign(PROVIDER_TRANSLATIONS.vi!, extension.vi);
}
