/* Generated by scripts/discover-providers.mjs. Do not edit. Server only. */
import { registerClaudeCode } from '../claude-code';
import { registerElevenlabs } from '../elevenlabs';
import { registerOllama } from '../ollama';
import { registerPiper } from '../piper';
import { registerSystemTts } from '../system-tts';
import { registerVbee } from '../vbee';

/** Every provider factory, registered once. Each registration is a Map.set: setting it twice is setting it once. */
export function installProviders(): void {
  registerClaudeCode();
  registerElevenlabs();
  registerOllama();
  registerPiper();
  registerSystemTts();
  registerVbee();
}
