/* Generated by scripts/discover-capsules.mjs. Do not edit. */
'use client';
import type React from 'react';
import type { BodyProps, NodeMeta } from '@/capsules/sdk/meta';
import { AssembleBody } from '../assemble/body';
import { AssetsBody, AssetsDialog } from '../assets/body';
import { BriefBody } from '../brief/body';
import { CaptionExportBody } from '../caption-export/body';
import { CompositionBody, PartsDialog } from '../composition/body';
import { CoverageBody } from '../coverage/body';
import { FillBody } from '../fill/body';
import { FootageBody } from '../footage/body';
import { MatteBody } from '../matte/body';
import { ExportBody } from '../mp4-export/body';
import { ResearchBody } from '../research/body';
import { RoughCutBody } from '../rough-cut/body';
import { StoryboardWriterBody } from '../storyboard-writer/body';
import { TranscribeBody } from '../transcribe/body';
import { TtsBody } from '../tts/body';
import { VideoOutputBody } from '../video-output/body';

export const NODE_BODIES: Record<string, React.FC<BodyProps>> = {
  'assemble': AssembleBody,
  'assets': AssetsBody,
  'brief': BriefBody,
  'caption-export': CaptionExportBody,
  'composition': CompositionBody,
  'coverage': CoverageBody,
  'fill': FillBody,
  'footage': FootageBody,
  'matte': MatteBody,
  'mp4-export': ExportBody,
  'research': ResearchBody,
  'rough-cut': RoughCutBody,
  'storyboard-writer': StoryboardWriterBody,
  'transcribe': TranscribeBody,
  'tts': TtsBody,
  'video-output': VideoOutputBody,
};

export const NODE_OVERLAYS: React.FC[] = [
  AssetsDialog,
  PartsDialog,
];

export const NODE_META: Record<string, NodeMeta> = {
  'assemble': { icon: 'layers', group: 'visual' },
  'assets': { icon: 'image', group: 'source', layout: 'wide' },
  'brief': { icon: 'doc', group: 'source', layout: 'wide' },
  'caption-export': { icon: 'down', group: 'output' },
  'composition': { icon: 'layers', group: 'visual', layout: 'wide' },
  'coverage': { icon: 'layers', group: 'script' },
  'fill': { icon: 'layers', group: 'visual' },
  'footage': { icon: 'film', group: 'source', layout: 'wide' },
  'matte': { icon: 'film', group: 'visual', layout: 'wide' },
  'mp4-export': { icon: 'down', group: 'output' },
  'research': { icon: 'search', group: 'script', layout: 'wide' },
  'rough-cut': { icon: 'branch', group: 'script' },
  'storyboard-writer': { icon: 'bot', group: 'script', layout: 'wide' },
  'transcribe': { icon: 'wave', group: 'audio' },
  'tts': { icon: 'wave', group: 'audio' },
  'video-output': { icon: 'screen', group: 'output', layout: 'wide' },
};

