/* Generated by scripts/discover-capsules.mjs. Do not edit. */
'use client';
import type React from 'react';
import type { BodyProps, NodeMeta } from '@/capsules/sdk/meta';
import { CaptionExportBody } from '../caption-export/body';
import { ExportBody } from '../mp4-export/body';
import { TranscribeBody } from '../transcribe/body';
import { TtsBody } from '../tts/body';
import { VideoOutputBody } from '../video-output/body';

export const NODE_BODIES: Record<string, React.FC<BodyProps>> = {
  'caption-export': CaptionExportBody,
  'mp4-export': ExportBody,
  'transcribe': TranscribeBody,
  'tts': TtsBody,
  'video-output': VideoOutputBody,
};

export const NODE_OVERLAYS: React.FC[] = [

];

export const NODE_META: Record<string, NodeMeta> = {
  'caption-export': { icon: 'down', group: 'output' },
  'mp4-export': { icon: 'down', group: 'output' },
  'transcribe': { icon: 'wave', group: 'audio' },
  'tts': { icon: 'wave', group: 'audio' },
  'video-output': { icon: 'screen', group: 'output', layout: 'wide' },
};

