/* Generated by scripts/discover-capsules.mjs. Do not edit. */
import { registerNodeType, registerRetiredNodeType, type AnyNodeDefinition, type RetiredNodeType } from '@/core/nodes/definition';
import { registerContracts } from '@/contracts';
import { registerDocMigrations } from '../../migrations';
import { assemble } from '../assemble/node';
import { assets } from '../assets/node';
import { brief } from '../brief/node';
import { captionExport } from '../caption-export/node';
import { composition } from '../composition/node';
import { fill } from '../fill/node';
import { mp4Export } from '../mp4-export/node';
import { research } from '../research/node';
import { storyboardWriter } from '../storyboard-writer/node';
import { transcribe } from '../transcribe/node';
import { ttsEngine } from '../tts/node';
import { videoOutput } from '../video-output/node';
import { AssembleErrorCode } from '../assemble/errors';
import { AssetsErrorCode } from '../assets/errors';
import { BriefErrorCode } from '../brief/errors';
import { CaptionExportErrorCode } from '../caption-export/errors';
import { CompositionErrorCode } from '../composition/errors';
import { FillErrorCode } from '../fill/errors';
import { Mp4ExportErrorCode } from '../mp4-export/errors';
import { ResearchErrorCode } from '../research/errors';
import { StoryboardWriterErrorCode } from '../storyboard-writer/errors';
import { TranscribeErrorCode } from '../transcribe/errors';
import { TtsErrorCode } from '../tts/errors';

export const ALL_NODES: AnyNodeDefinition[] = [
  assemble,
  assets,
  brief,
  captionExport,
  composition,
  fill,
  mp4Export,
  research,
  storyboardWriter,
  transcribe,
  ttsEngine,
  videoOutput,
] as unknown as AnyNodeDefinition[];

const expectedIds = ["assemble","assets","brief","caption-export","composition","fill","mp4-export","research","storyboard-writer","transcribe","tts","video-output"];
ALL_NODES.forEach((definition, index) => {
  if (definition.type !== expectedIds[index]) throw new Error('node manifest id "' + expectedIds[index] + '" does not match definition type "' + definition.type + '"');
});

/** What a node declares about itself beyond its ports, for the hub: which node carries the IR, the preview, the file export. */
export const NODE_FEATURES: Record<string, string[]> = {
  "assemble": [],
  "assets": [],
  "brief": [],
  "caption-export": [],
  "composition": [],
  "fill": [],
  "mp4-export": [
    "history-file-export"
  ],
  "research": [],
  "storyboard-writer": [],
  "transcribe": [],
  "tts": [],
  "video-output": [
    "history-preview"
  ]
};

/**
 * The failures each capsule owns. A code that belongs to one node lives in that node's errors.ts
 * beside its strings in the capsule's own locales; core carries only what core and the provider
 * layer raise. Listed here so a test can check every one of them can be shown to a person.
 */
export const NODE_ERROR_CODES: Record<string, string[]> = {
  "assemble": [],
  "assets": [],
  "brief": [],
  "caption-export": [],
  "composition": [],
  "fill": [],
  "mp4-export": [],
  "research": [],
  "storyboard-writer": [],
  "transcribe": [],
  "tts": []
};
NODE_ERROR_CODES['assemble'] = Object.values(AssembleErrorCode);
NODE_ERROR_CODES['assets'] = Object.values(AssetsErrorCode);
NODE_ERROR_CODES['brief'] = Object.values(BriefErrorCode);
NODE_ERROR_CODES['caption-export'] = Object.values(CaptionExportErrorCode);
NODE_ERROR_CODES['composition'] = Object.values(CompositionErrorCode);
NODE_ERROR_CODES['fill'] = Object.values(FillErrorCode);
NODE_ERROR_CODES['mp4-export'] = Object.values(Mp4ExportErrorCode);
NODE_ERROR_CODES['research'] = Object.values(ResearchErrorCode);
NODE_ERROR_CODES['storyboard-writer'] = Object.values(StoryboardWriterErrorCode);
NODE_ERROR_CODES['transcribe'] = Object.values(TranscribeErrorCode);
NODE_ERROR_CODES['tts'] = Object.values(TtsErrorCode);

/** Node types that are gone, and what became of them (capsules/retired.json). */
export const RETIRED_NODES: Record<string, RetiredNodeType> = {
  "core/art-director": {
    "since": "2026-09-10"
  },
  "core/audio-analysis": {
    "since": "2026-09-14"
  },
  "core/audio-input": {
    "since": "2026-09-14"
  },
  "core/audio-mix": {
    "since": "2026-09-14"
  },
  "core/caption-export": {
    "renamedTo": "caption-export",
    "since": "2026-09-14"
  },
  "core/captions": {
    "since": "2026-09-12"
  },
  "core/cast": {
    "since": "2026-09-12"
  },
  "core/compose": {
    "since": "2026-09-14"
  },
  "core/cover-export": {
    "since": "2026-09-10"
  },
  "core/github-fetcher": {
    "since": "2026-09-13"
  },
  "core/hyperframes-engine": {
    "since": "2026-09-12"
  },
  "core/illustrator": {
    "since": "2026-09-13"
  },
  "core/input-trigger": {
    "since": "2026-09-14"
  },
  "core/layer": {
    "since": "2026-09-14"
  },
  "core/llm-provider": {
    "since": "2026-09-12"
  },
  "core/mp4-export": {
    "renamedTo": "mp4-export",
    "since": "2026-09-14"
  },
  "core/plates": {
    "since": "2026-09-14"
  },
  "core/scene-breakdown": {
    "since": "2026-09-14"
  },
  "core/screenwriter": {
    "since": "2026-09-14"
  },
  "core/set": {
    "since": "2026-09-14"
  },
  "core/static-script": {
    "since": "2026-09-14"
  },
  "core/stock-media": {
    "since": "2026-09-14"
  },
  "core/style": {
    "since": "2026-09-12"
  },
  "core/timeline-assembler": {
    "since": "2026-09-14"
  },
  "core/transcribe": {
    "renamedTo": "transcribe",
    "since": "2026-09-14"
  },
  "core/tts-engine": {
    "renamedTo": "tts",
    "since": "2026-09-14"
  },
  "core/tts-provider": {
    "since": "2026-09-12"
  },
  "core/video-output": {
    "renamedTo": "video-output",
    "since": "2026-09-14"
  },
  "core/web-fetcher": {
    "since": "2026-09-14"
  }
};

/** Nodes speak the video contracts, so registering them registers what runs on their wires first. */
export function registerNodes(): void {
  registerContracts();
  for (const definition of ALL_NODES) registerNodeType(definition);
  for (const [type, info] of Object.entries(RETIRED_NODES)) registerRetiredNodeType(type, info);
  registerDocMigrations();
}
