/* Generated by scripts/discover-capsules.mjs. Do not edit. */
import { assembleTranslations } from '../assemble/locales';
import { assetsTranslations } from '../assets/locales';
import { captionExportTranslations } from '../caption-export/locales';
import { compositionTranslations } from '../composition/locales';
import { fillTranslations } from '../fill/locales';
import { mp4ExportTranslations } from '../mp4-export/locales';
import { scriptTranslations } from '../script/locales';
import { storyboardWriterTranslations } from '../storyboard-writer/locales';
import { transcribeTranslations } from '../transcribe/locales';
import { ttsTranslations } from '../tts/locales';
import { videoOutputTranslations } from '../video-output/locales';

/** Every string a node shows, by language: its name and description (node.<id>, node.desc.<id>) and its own labels. */
export const NODE_TRANSLATIONS: Record<string, Record<string, string>> = { en: {}, vi: {} };
for (const extension of [assembleTranslations, assetsTranslations, captionExportTranslations, compositionTranslations, fillTranslations, mp4ExportTranslations, scriptTranslations, storyboardWriterTranslations, transcribeTranslations, ttsTranslations, videoOutputTranslations]) {
  Object.assign(NODE_TRANSLATIONS.en!, extension.en);
  Object.assign(NODE_TRANSLATIONS.vi!, extension.vi);
}
