/* Generated by scripts/discover-capsules.mjs. Do not edit. Server only. */
import type { NodeService } from '@/core/engine/services';
import { assetsServices } from '../assets/server';
import { compositionServices, compositionActions } from '../composition/server';
import { footageServices } from '../footage/server';
import { matteServices } from '../matte/server';
import { researchServices } from '../research/server';
import { transcribeServices } from '../transcribe/server';
import { ttsActions } from '../tts/server';

export const NODE_SERVICE_EXTENSIONS: Record<string, NodeService>[] = [
  assetsServices,
  compositionServices,
  footageServices,
  matteServices,
  researchServices,
  transcribeServices,
];

/**
 * What a node's body may ask the server for while a person edits it, outside any run: installing a
 * part into a composition, say. Kept apart from the services so only what a capsule names as an
 * action is reachable from the canvas.
 */
export const NODE_ACTIONS: Record<string, NodeService>[] = [
  compositionActions,
  ttsActions,
];

/**
 * The capsule folder of each node type. The server fingerprints the code that runs the node from it:
 * every file there but its tests and its face, and whatever those import (server/fingerprints.ts).
 */
export const NODE_SOURCES: Record<string, string> = {
  "assemble": "capsules/nodes/assemble",
  "assets": "capsules/nodes/assets",
  "brief": "capsules/nodes/brief",
  "caption-export": "capsules/nodes/caption-export",
  "composition": "capsules/nodes/composition",
  "coverage": "capsules/nodes/coverage",
  "fill": "capsules/nodes/fill",
  "footage": "capsules/nodes/footage",
  "matte": "capsules/nodes/matte",
  "mp4-export": "capsules/nodes/mp4-export",
  "research": "capsules/nodes/research",
  "rough-cut": "capsules/nodes/rough-cut",
  "storyboard-writer": "capsules/nodes/storyboard-writer",
  "transcribe": "capsules/nodes/transcribe",
  "tts": "capsules/nodes/tts",
  "video-output": "capsules/nodes/video-output"
};
