/* Generated by scripts/discover-capsules.mjs. Do not edit. Server only. */
import type { NodeService } from '@/core/engine/services';
import { compositionServices } from '../composition/server';
import { transcribeServices } from '../transcribe/server';

export const NODE_SERVICE_EXTENSIONS: Record<string, NodeService>[] = [
  compositionServices,
  transcribeServices,
];

/**
 * The capsule folder of each node type. The server fingerprints the code that runs the node from it:
 * every file there but its tests and its face, and whatever those import (server/fingerprints.ts).
 */
export const NODE_SOURCES: Record<string, string> = {
  "caption-export": "capsules/nodes/caption-export",
  "composition": "capsules/nodes/composition",
  "fill": "capsules/nodes/fill",
  "mp4-export": "capsules/nodes/mp4-export",
  "transcribe": "capsules/nodes/transcribe",
  "tts": "capsules/nodes/tts",
  "video-output": "capsules/nodes/video-output"
};
